#!/bin/sh

SCRIPT_LOCATION="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo 'Cleaning up build artifacts...'
cd "$SCRIPT_LOCATION" || (echo 'Failed to find project root directory' && exit 1)
rm -rf debian/.debhelper
rm -rf debian/openmediavault-*
rm -f debian/debhelper-build-stamp
rm -f debian/files
rm -f debian/*.substvars
rm -f debian/*.deb
echo 'Build artifacts cleaned up successfully'